version: "3.9"
services:
  backend:
    build:
      context: "be/"
      dockerfile: Dockerfile
    networks:
      - axum_spa_network
    ports:
      - "8080:8080"

  frontend:
    build:
      context: "fe/"
      dockerfile: Dockerfile
    networks:
      - axum_spa_network
    ports:
      - "80:80"

networks:
  axum_spa_network:
