version: "3.9"
services:
  backend:
    build:
      context: "be/"
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "8080:8080"

  frontend:
    build:
      context: "fe/"
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "80:80"

networks:
  default:
    driver: bridge
